import type { Metadata } from "next";
import { Providers } from "./_components/providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "AI WEBSITE BUILDER",
  description: "Generated by PRASHANT VERMA",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
